#!/usr/bin/env bash

# Original work by FND
# https://github.com/fnd/todo.txt-cli/blob/extensions/edit

# Modified by f6k (20/12/16)

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [ITEM]"
    echo "      Open vi text editor at ITEM line. If no ITEM is provided, it will simply"
    echo "      open the todo.txt file."
    echo ""
    exit
}

COMMAND=${EDITOR:-vi}
if [[ "$1" =~ ^[0-9]+$ ]]; then
	COMMAND="$COMMAND +$1"
else
  COMMAND="$COMMAND"
fi

$COMMAND "$TODO_FILE"
